# Git Hook Setup Script for AI Job Generation
# This script sets up a post-commit hook that can optionally trigger job generation

param(
    [switch]$AutoGenerate,  # Enable automatic job generation on commit
    [switch]$Remove         # Remove the hook
)

$hookPath = ".git\hooks\post-commit"
$projectRoot = $PSScriptRoot | Split-Path -Parent

Write-Host "`n🔧 Git Hook Setup for AI Job Generation`n" -ForegroundColor Cyan
Write-Host "=" * 60

if ($Remove) {
    if (Test-Path $hookPath) {
        Remove-Item $hookPath -Force
        Write-Host "`n✅ Post-commit hook removed successfully`n" -ForegroundColor Green
    } else {
        Write-Host "`n⚠️  No post-commit hook found`n" -ForegroundColor Yellow
    }
    exit 0
}

# Create the post-commit hook
$hookContent = @"
#!/bin/sh
# Auto-generated post-commit hook for AI job generation
# Generated by setup-job-generation-hook.ps1

# Configuration
AUTO_GENERATE=$($AutoGenerate.IsPresent.ToString().ToLower())
PROJECT_ROOT="$projectRoot"

echo ""
echo "📊 Post-commit: AI Job Generation System"
echo ""

if [ "$AUTO_GENERATE" = "true" ]; then
    echo "🤖 Auto-generating job postings from this commit..."
    echo ""

    # Run the job generator in preview mode
    cd "$PROJECT_ROOT"
    npm run generate-jobs -- --count 1 --preview

    echo ""
    echo "ℹ️  Jobs generated in preview mode (not saved)."
    echo "   To save jobs, run: npm run generate-jobs -- --save"
    echo ""
else
    echo "ℹ️  Auto-generation disabled."
    echo "   To generate jobs, run: npm run generate-jobs"
    echo ""
    echo "   To enable auto-generation, run:"
    echo "   powershell -ExecutionPolicy Bypass -File ./scripts/setup-job-generation-hook.ps1 -AutoGenerate"
    echo ""
fi
"@

# Ensure .git/hooks directory exists
$hooksDir = ".git\hooks"
if (-not (Test-Path $hooksDir)) {
    New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null
}

# Write the hook file
$hookContent | Out-File -FilePath $hookPath -Encoding ASCII -Force

# Make it executable (Windows doesn't need this, but good for cross-platform)
# Git for Windows respects the execute bit in the index

Write-Host "`n✅ Post-commit hook installed successfully!`n" -ForegroundColor Green

if ($AutoGenerate) {
    Write-Host "🤖 Auto-generation: ENABLED" -ForegroundColor Green
    Write-Host "   Jobs will be analyzed (preview mode) after each commit.`n"
} else {
    Write-Host "ℹ️  Auto-generation: DISABLED" -ForegroundColor Yellow
    Write-Host "   You'll see a reminder after each commit.`n"
}

Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Hook location: $hookPath"
Write-Host "  Project root: $projectRoot"
Write-Host ""

Write-Host "To enable auto-generation:" -ForegroundColor Yellow
Write-Host "  powershell -ExecutionPolicy Bypass -File ./scripts/setup-job-generation-hook.ps1 -AutoGenerate"
Write-Host ""

Write-Host "To disable/remove hook:" -ForegroundColor Yellow
Write-Host "  powershell -ExecutionPolicy Bypass -File ./scripts/setup-job-generation-hook.ps1 -Remove"
Write-Host ""

Write-Host "To manually generate jobs:" -ForegroundColor Yellow
Write-Host "  npm run generate-jobs              # Preview mode"
Write-Host "  npm run generate-jobs -- --save    # Save to Firestore"
Write-Host ""
